return {

    ClientAudios = {
        ["Pop"] = "rbxassetid://1289263994",
        ["Bought"] = "rbxassetid://7437419566",
        ["Pop Up"] = "rbxassetid://17481582653",
        ["Typing"] = "rbxassetid://9116156872",
    },

    BackgroundMusic = {

        ["Morning Mood"] = "rbxassetid://1846088038",
        ["Nocturnal"] = "rbxassetid://1848028342",
        ["Classical"] = "rbxassetid://9045766074",
        ["Arabesque"] = "rbxassetid://9045764969",

    }




}